/* Generated by AN DISI Unibo */ 
package it.unibo.planexec

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Planexec ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		  var Plan          = ""
				var PlanOrig      = ""
				var CurMoveTodo   = ""		
				var StepTime      = "200"
				var OwnerMngr     = supports.OwnerManager //Kotlin object
				var IsOwner       = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						subscribeToLocalActor("engager") 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t06",targetState="checkTheOwner",cond=whenRequest("doplan"))
				}	 
				state("checkTheOwner") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("doplan(PATH,STEPTIME)"), Term.createTerm("doplan(PLAN,STEPTIME)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Plan       = payloadArg(0).replace("[","").replace("]","").replace(",","").replace(" ","")
											   PlanOrig   = Plan
											   StepTime   = payloadArg(1) 
								    		   val Caller = currentMsg.msgSender() //payloadArg(1) 
								    		   IsOwner    = OwnerMngr.checkOwner( Caller )
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="nextMove", cond=doswitchGuarded({ IsOwner  
					}) )
					transition( edgeName="goto",targetState="planrefused", cond=doswitchGuarded({! ( IsOwner  
					) }) )
				}	 
				state("nextMove") { //this:State
					action { //it:State
						 
								   if( Plan.length > 0  ){
								   	CurMoveTodo =  Plan.elementAt(0).toString() 
								   	Plan        =  Plan.removePrefix(CurMoveTodo)
								   }else{
								   	CurMoveTodo = ""
								   	Plan        = "empty"
								   } 		   
						if(  CurMoveTodo == ""  
						 ){forward("nomoremove", "nomoremove(end)" ,"planexec" ) 
						}
						else
						 {if(  CurMoveTodo == "w"  
						  ){delay(300) 
						 request("step", "step($StepTime)" ,"basicrobot" )  
						 }
						 else
						  {uniborobots.robotSupport.move( CurMoveTodo  )
						  forward("nextmove", "nextmove(goon)" ,"planexec" ) 
						  }
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="planinterruptedobstacle",cond=whenReply("stepfailed"))
					transition(edgeName="t08",targetState="planinterruptedalarm",cond=whenEvent("alarm"))
					transition(edgeName="t09",targetState="planend",cond=whenDispatch("nomoremove"))
					transition(edgeName="t010",targetState="nextMove",cond=whenDispatch("nextmove"))
					transition(edgeName="t011",targetState="nextMove",cond=whenReply("stepdone"))
				}	 
				state("planend") { //this:State
					action { //it:State
						if(  currentMsg.msgContent() == "alarm(disengaged)"  
						 ){}
						else
						 {if(  currentMsg.msgId() == "alarm"  
						  ){CommUtils.outblack("$name |  planend alarm $Plan $CurMoveTodo")
						  val Plantodo = CurMoveTodo + Plan  
						 answer("doplan", "doplanfailed", "doplanfailed($Plantodo)"   )  
						 }
						 else
						  {CommUtils.outblue("$name | planend ok plan=$PlanOrig ")
						  answer("doplan", "doplandone", "doplandone($PlanOrig)"   )  
						  updateResourceRep( "plandone($PlanOrig)"  
						  )
						  }
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("planinterruptedobstacle") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name |  planinterruptedobstacle $CurMoveTodo ")
						 var Plantodo =  CurMoveTodo + Plan
						updateResourceRep( "planfailed($PlanOrig,$Plantodo )"  
						)
						answer("doplan", "doplanfailed", "doplanfailed($Plantodo)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("planinterruptedalarm") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t012",targetState="nonextmovesincealarm",cond=whenDispatch("nextmove"))
					transition(edgeName="t013",targetState="nonextmovesincealarm",cond=whenReply("stepdone"))
					transition(edgeName="t014",targetState="planinterruptedobstacle",cond=whenReply("stepfailed"))
				}	 
				state("nonextmovesincealarm") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name |  nonextmovesincealarm $CurMoveTodo plantodo=$Plan")
						updateResourceRep( "planfailed($PlanOrig,$Plan )"  
						)
						if(  Plan.length == 0  
						 ){answer("doplan", "doplandone", "doplandone($PlanOrig)"   )  
						}
						else
						 {answer("doplan", "doplanfailed", "doplanfailed($Plan)"   )  
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("planrefused") { //this:State
					action { //it:State
						answer("doplan", "doplanfailed", "doplanfailed(youarenotowner)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
}
