/* Generated by AN DISI Unibo */ 
package it.unibo.planexec

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Planexec ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		  var Plan          = ""
				var CurMoveTodo   = ""		
				//var StepSynchRes  = false
				var StepTime      = 345L
				var Owner         = "unknown"
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						subscribeToLocalActor("engager") 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="execplan",cond=whenRequest("doplan"))
				}	 
				state("execplan") { //this:State
					action { //it:State
						CommUtils.outred("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("doplan(PATH,OWNER,STEPTIME)"), Term.createTerm("doplan(PLAN,OWNER,STEPTIME)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outblue("$name | ${payloadArg(0)}")
								  Plan     = payloadArg(0).replace("[","").replace("]","").replace(",","").replace(" ","")
												Owner    = payloadArg(1)
												StepTime = payloadArg(2).toLong()
								CommUtils.outblue("$name | Plan=$Plan StepTime=$StepTime")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_execplan", 
				 	 					  scope, context!!, "local_tout_planexec_execplan", 100.toLong() )
					}	 	 
					 transition(edgeName="t09",targetState="nextMove",cond=whenTimeout("local_tout_planexec_execplan"))   
					transition(edgeName="t010",targetState="planinterrupted",cond=whenEvent("alarm"))
				}	 
				state("nextMove") { //this:State
					action { //it:State
						 
								   if( Plan.length > 0  ){
								   	CurMoveTodo =  Plan.elementAt(0).toString() 
								   	Plan        =  Plan.removePrefix(CurMoveTodo)
								   }else CurMoveTodo = ""		   
						CommUtils.outblue("$name | CurMoveTodo= $CurMoveTodo remain:$Plan")
						forward("nextmove", "nextmove($CurMoveTodo)" ,"planexec" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t011",targetState="planinterrupted",cond=whenEvent("alarm"))
					transition(edgeName="t012",targetState="doMove",cond=whenDispatch("nextmove"))
				}	 
				state("doMove") { //this:State
					action { //it:State
						CommUtils.outblue("$name | domove $CurMoveTodo")
						if(  CurMoveTodo == ""  
						 ){forward("nomoremove", "nomoremove(end)" ,"planexec" ) 
						}
						else
						 {if(  CurMoveTodo == "w"  
						  ){delay(300) 
						 request("step", "step($StepTime)" ,"basicrobot" )  
						 }
						 else
						  {CommUtils.outblue("doMoveTurn $CurMoveTodo")
						  uniborobots.robotSupport.move( CurMoveTodo  )
						  forward("nextmove", "nextmove(goon)" ,"planexec" ) 
						  }
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t013",targetState="planinterrupted",cond=whenEvent("alarm"))
					transition(edgeName="t014",targetState="planend",cond=whenDispatch("nomoremove"))
					transition(edgeName="t015",targetState="nextMove",cond=whenDispatch("nextmove"))
					transition(edgeName="t016",targetState="nextMove",cond=whenReply("stepdone"))
					transition(edgeName="t017",targetState="planinterrupted",cond=whenReply("stepfailed"))
				}	 
				state("planend") { //this:State
					action { //it:State
						CommUtils.outred("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if(  currentMsg.msgContent() == "alarm(disengaged)"  
						 ){}
						else
						 {if(  currentMsg.msgId() == "alarm"  
						  ){CommUtils.outblue("planend alarm ")
						  val Pathtodo = CurMoveTodo + Plan  
						 answer("doplan", "doplanfailed", "doplanfailed($Pathtodo)"   )  
						 }
						 else
						  {CommUtils.outblue("planend ok ")
						  answer("doplan", "doplandone", "doplandone(ok)"   )  
						  updateResourceRep( "plandone($Plan)"  
						  )
						  }
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("planinterrupted") { //this:State
					action { //it:State
						CommUtils.outmagenta("pathinterrupted  ")
						 var Pathtodo = "" 
						 		   //if( StepSynchRes ) Pathtodo = Plan  
						 		   //else Pathtodo = CurMoveTodo + Plan 	
						 		   Pathtodo = CurMoveTodo + Plan
						updateResourceRep( "planfailed($Plan,$Pathtodo )"  
						)
						answer("doplan", "doplanfailed", "doplanfailed($Pathtodo)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
}
