/* Generated by AN DISI Unibo */ 
package it.unibo.corecaller1

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Corecaller1 ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		 var StartTime = 0L 
		  	   var Elapsed   = 0L
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						request("cmd", "cmd(1)" ,"resourcecore" )  
						StartTime = getCurrentTime()
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleReply",cond=whenReply("replytocmd"))
				}	 
				state("handleReply") { //this:State
					action { //it:State
						CommUtils.outblue("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						Elapsed = getDuration(StartTime)
						CommUtils.outblue("$name handleReply Elapsed = $Elapsed ")
						CommUtils.outred("$name handleReply: emit alarm(on)")
						emit("alarm", "alarm(on)" ) 
						request("cmd", "cmd(2)" ,"resourcecore" )  
						request("cmd", "cmd(3)" ,"resourcecore" )  
						StartTime = getCurrentTime()
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="handleReplyAgain",cond=whenReply("replytocmd"))
				}	 
				state("handleReplyAgain") { //this:State
					action { //it:State
						CommUtils.outblue("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						Elapsed = getDuration(StartTime)
						CommUtils.outblue("$name handleReplyAgain Elapsed = $Elapsed ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="handleReplyAgain",cond=whenReply("replytocmd"))
				}	 
			}
		}
}
