/* Generated by AN DISI Unibo */ 
package it.unibo.robotposendosimbiotico

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Robotposendosimbiotico ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		 val planner = unibo.planner23.Planner23Util()
			    //val MapName = "mapEmpty23"
			    val MapName = "mapCompleteWithObst23ok"
			    val MyName    = name //upcase var
			    var StepTime  = "330"
				var Plan      = ""	
				var Caller    = ""
				var TargetX   = ""
				var TargetY   = ""
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblack("$name STARTS loading $MapName")
						 StepTime = uniborobots.robotSupport.readStepTime( )	 		
						 planner.initAI()  
								   planner.loadRoomMap(MapName) 
								   planner.showMap()
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitclientrequest", cond=doswitch() )
				}	 
				state("waitclientrequest") { //this:State
					action { //it:State
						CommUtils.outblack("$name | waiting the client request...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t021",targetState="getRoboSstate",cond=whenRequest("getrobotstate"))
					transition(edgeName="t022",targetState="checkTheOwnerForMove",cond=whenRequest("moverobot"))
					transition(edgeName="t023",targetState="checkTheOwnerForSet",cond=whenDispatch("setrobotstate"))
				}	 
				state("getRoboSstate") { //this:State
					action { //it:State
						 val PX   = planner.getPosX() 
						    		val PY  = planner.getPosY()
						    		val DIR = ""+planner.getDir()
						answer("getrobotstate", "robotstate", "robotstate(pos($PX,$PY),$DIR)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitclientrequest", cond=doswitch() )
				}	 
				state("checkTheOwnerForSet") { //this:State
					action { //it:State
						 Caller = currentMsg.msgSender()  
						request("checkowner", "checkowner($Caller)" ,"engager" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t024",targetState="setTheRobotState",cond=whenReply("checkownerok"))
					transition(edgeName="t025",targetState="waitclientrequest",cond=whenReply("checkownerfailed"))
				}	 
				state("setTheRobotState") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("setpos(X,Y,D)"), Term.createTerm("setpos(X,Y,D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val X = payloadArg(0)
											   val Y = payloadArg(1)
											   val D = payloadArg(2)
											   planner.setRobotState(X,Y,D) 
								CommUtils.outmagenta("setTheRobotState ($X, $Y, $D) ")
								 planner.showCurrentRobotState();  
						}
						delay(300) 
						CommUtils.outmagenta("update resource for setTheRobotState")
						updateResourceRep( planner.robotOnMap()  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitclientrequest", cond=doswitch() )
				}	 
				state("checkTheOwnerForMove") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						 Caller = currentMsg.msgSender()  
						if( checkMsgContent( Term.createTerm("moverobot(TARGETX,TARGETY)"), Term.createTerm("moverobot(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 TargetX = payloadArg(0)
											   TargetY = payloadArg(1)
						}
						CommUtils.outblue("$name checkTheOwnerForMove $Caller")
						request("checkowner", "checkowner($Caller)" ,"engager" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t026",targetState="planTheRobotmoves",cond=whenReply("checkownerok"))
					transition(edgeName="t027",targetState="moveRefused",cond=whenReply("checkownerfailed"))
				}	 
				state("elabClientRequest") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="planTheRobotmoves", cond=doswitch() )
				}	 
				state("planTheRobotmoves") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						  
								   Plan = planner.planForGoal(""+TargetX,""+TargetY).toString()
								   println("planTheRobotmoves $Plan")
								   Plan = planner.planCompacted(Plan) 
								   if( Plan.isEmpty()) Plan="''"
								   //CommUtils.outblue("$name | Plan to reach pos: $Plan")
						CommUtils.outblue("$name | Plan to reach pos: $Plan for $Caller")
						request("doplan", "doplan($Plan,$Caller,$StepTime)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t028",targetState="endok",cond=whenReply("doplandone"))
					transition(edgeName="t029",targetState="endko",cond=whenReply("doplanfailed"))
				}	 
				state("endok") { //this:State
					action { //it:State
						CommUtils.outblack("pos reached")
						 planner.doPathOnMap(Plan)  
						 planner.showCurrentRobotState();  
						updateResourceRep( planner.robotOnMap()  
						)
						answer("moverobot", "moverobotdone", "moverobotdone(ok)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitclientrequest", cond=doswitch() )
				}	 
				state("endko") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("doplanfailed(ARG)"), Term.createTerm("doplanfailed(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val PathTodo = payloadArg(0)  
								CommUtils.outred("pos NOT reached - PathTodo = ${PathTodo} vs. $Plan")
								   var PathDone = Plan.substring(0, Plan.lastIndexOf(PathTodo))
												 if( PathDone == "" ) PathDone ="n"				 
												 else planner.doPathOnMap(PathDone)
								updateResourceRep( planner.robotOnMap()  
								)
								CommUtils.outblack("uuu ${PathDone}")
								 planner.showCurrentRobotState();  
								answer("moverobot", "moverobotfailed", "moverobotfailed($PathDone,$PathTodo)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitclientrequest", cond=doswitch() )
				}	 
				state("moveRefused") { //this:State
					action { //it:State
						answer("moverobot", "moverobotfailed", "moverobotfailed(none,refused)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitclientrequest", cond=doswitch() )
				}	 
			}
		}
}
