/* Generated by AN DISI Unibo */ 
package it.unibo.basicrobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Basicrobot ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "ss0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		  
		  var StepTime      = 0L
		  var StartTime     = 0L     
		  var Duration      = 0L   
		  var RobotType     = "" 
		  var CurrentMove   = "unkknown"
		  var StepSynchRes  = false
		  var Owner         = "unkknown"
		  
		  fun checkOwner() : Boolean {
		  	CommUtils.outblue("                    checkOwner $Owner ${currentMsg}")
		  	return ( currentMsg.msgContent().contains( Owner ) || currentMsg.isEvent() )
		  }
		return { //this:ActionBasciFsm
				state("ss0") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						discardMessages = true
						delegate("engage", "engager") 
						CommUtils.outblack("basicrobot | STARTS")
						uniborobots.robotSupport.create(myself ,"basicrobotConfig.json" )
						 RobotType = uniborobots.robotSupport.robotKind  
						uniborobots.robotSupport.move( "a"  )
						uniborobots.robotSupport.move( "d"  )
						updateResourceRep( "basicrobot(started)"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t04",targetState="work",cond=whenDispatch("engaged"))
				}	 
				state("work") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						discardMessages = false
						if( checkMsgContent( Term.createTerm("engaged(ARG)"), Term.createTerm("engaged(OWNER)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Owner  = payloadArg(0)  
						}
						CommUtils.outblack("basicrobot  | waiting .................. ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t05",targetState="doStep",cond=whenRequest("step"))
					transition(edgeName="t06",targetState="execcmd",cond=whenDispatchGuarded("cmd",{ checkOwner()   
					}))
					transition(edgeName="t07",targetState="endwork",cond=whenDispatchGuarded("end",{ checkOwner()   
					}))
				}	 
				state("execcmd") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("cmd(MOVE)"), Term.createTerm("cmd(MOVE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CurrentMove = payloadArg(0)  
								uniborobots.robotSupport.move( payloadArg(0)  )
								updateResourceRep( "moveactivated(${payloadArg(0)})"  
								)
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("doStep") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("step(TIME)"), Term.createTerm("step(T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
									StepTime     = payloadArg(0).toLong()  	 
								updateResourceRep( "step(${StepTime})"  
								)
						}
						StartTime = getCurrentTime()
						CommUtils.outblack("basicrobot | doing doStep StepTime=$StepTime  ")
						 StepSynchRes = uniborobots.robotSupport.dostep( StepTime )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="stepok", cond=doswitchGuarded({ StepSynchRes  
					}) )
					transition( edgeName="goto",targetState="stepKo", cond=doswitchGuarded({! ( StepSynchRes  
					) }) )
				}	 
				state("stepok") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						uniborobots.robotSupport.move( "h"  )
						updateResourceRep( "stepDone($StepTime)"  
						)
						answer("step", "stepdone", "stepdone($StepTime)"   )  
						CommUtils.outblack("basicrobot | stepDone reply done")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("stepKo") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						Duration = getDuration(StartTime)
						uniborobots.robotSupport.move( "h"  )
						 var TunedDuration   =  ((Duration * 0.80)).toLong()    
						CommUtils.outblack("basicrobot | stepFail duration=$Duration  TunedDuration=$TunedDuration")
						uniborobots.robotSupport.move( "s"  )
						delay(TunedDuration)
						uniborobots.robotSupport.move( "h"  )
						updateResourceRep( "stepFail($Duration)"  
						)
						answer("step", "stepfailed", "stepfailed($Duration,obst)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("endwork") { //this:State
					action { //it:State
						updateResourceRep( "basicrobot(end)"  
						)
						terminate(1)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
}
