version: '3'
services:
  webrobot23:
    #image: imgwebrobot23:1.0
    image: docker.io/natbodocker/imgwebrobot23:1.0
    ports:
      - 8085:8085/tcp
  basicrobot23:
    #image:  imgbasicrobot23:1.0
    image: docker.io/natbodocker/imgbasicrobot23:1.0
    privileged : true
    ports:
      - 8020:8020/tcp
      - 8080:8080



## -------------------------------------------------------------
## TODO See https://docs.docker.com/compose/startup-order/
## -------------------------------------------------------------
## docker-compose -f webbasicrobotonRasp23.yaml  up
